/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class karmaresearch_trident_Trident */

#ifndef _Included_karmaresearch_trident_Trident
#define _Included_karmaresearch_trident_Trident
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     karmaresearch_trident_Trident
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_karmaresearch_trident_Trident_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     karmaresearch_trident_Trident
 * Method:    sparql
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_karmaresearch_trident_Trident_sparql
  (JNIEnv *, jobject, jstring);

/*
 * Class:     karmaresearch_trident_Trident
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_karmaresearch_trident_Trident_unload
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
